##
# FONTCUSTOM CONFIG
#
# Include this file along with your vectors or pass it to any command with:
#   --config=path/to/config.yml 
#   -c path/to/containing/dir/
#
# Run `fontcustom help` to learn about various options
##

output:
  fonts: source/stylesheets/fonts
  css: source/stylesheets

# templates: [ scss, preview, relative/path/from/INPUT, relative/path/from/PWD ]
templates: [ css ]

# font_name: my-font

no_hash: false

#css_prefix: glyph-

#debug: true

#verbose: false
