input: source/images/icons
output:
  fonts: source/stylesheets/fonts
  css: source/stylesheets
# templates: [ scss, preview, relative/path/from/INPUT, relative/path/from/PWD ]
templates: [ scss ]
no_hash: false
css_prefix: icon-{{glyph}}
autowidth: true
font_name: fontcustom
# debug: true
# verbose: true
preprocessor_path: "/stylesheets/fonts"
